---
  - name: Provision new server on VMware
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      folder: "/ocp"
      esxi_hostname: "{{ esx_host }}"
      datacenter: "{{ vc_datacenter }}"
      name: "{{ vm_name }}"
      state: poweredon
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_vcpu }}"
      template: "{{ template_name }}"
      networks:
      - name: VM Network
        dns_servers:
        - "{{ dns1 }}"
        device_type: vmxnet3
        type: static
        ip: "{{ vm_nic1_ip }}"
        netmask: "{{ vm_nic1_netmask }}"
        gateway: "{{ vm_nic1_gw }}"
      customization:
        dns_servers:
        - "{{ dns1 }}"
        domain: "{{ domain }}"
        hostname: "{{ vm_name }}"
        runonce: 
        - hostnamectl set-hostname "{{ vm_name }}"."{{ domain }}"
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy

  - name: Debugging instance info
    debug: var=deploy.results[0]
